# Generated by Django 6.0.2 on 2026-03-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='depart_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='depart_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
