# Generated by Django 6.0.2 on 2026-03-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0002_trajet_depart_lat_trajet_depart_lng_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trajet',
            options={'ordering': ['-date_heure_depart']},
        ),
        migrations.AddField(
            model_name='trajet',
            name='distance_km',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='escales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trajet',
            name='est_regulier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trajet',
            name='jours_semaine',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart_lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='destination_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='destination_lng',
            field=models.FloatField(),
        ),
    ]
