# Generated by Django 6.0.2 on 2026-03-06 12:48

import apps.modeles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0003_alter_trajet_options_trajet_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='cout_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=apps.modeles.models.chemin_photo),
        ),
    ]
