# Generated by Django 6.0.2 on 2026-03-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0004_trajet_cout_total_alter_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
