# Generated by Django 6.0.2 on 2026-04-06 10:33

import apps.modeles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0005_alter_trajet_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducteur',
            name='couleur_vehicule',
        ),
        migrations.RemoveField(
            model_name='conducteur',
            name='plaque',
        ),
        migrations.RemoveField(
            model_name='conducteur',
            name='type_vehicule',
        ),
        migrations.RemoveField(
            model_name='conducteur',
            name='vehicule',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='escales',
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=apps.modeles.models.chemin_photo),
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('minibus', 'Minibus'), ('camion', 'Camion')], max_length=20)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=50)),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('places_max', models.IntegerField()),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='modeles.conducteur')),
            ],
        ),
        migrations.AddField(
            model_name='trajet',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets', to='modeles.vehicule'),
        ),
    ]
