# Generated by Django 6.0.2 on 2026-05-08 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0006_remove_conducteur_couleur_vehicule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='ouvert', max_length=20),
        ),
        migrations.CreateModel(
            name='PositionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('vitesse_kmh', models.FloatField(blank=True, null=True)),
                ('direction', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_gps', to='modeles.trajet')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trajet', '-timestamp'], name='modeles_pos_trajet__3118eb_idx')],
            },
        ),
    ]
