# Generated by Django 6.0.2 on 2026-05-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0007_alter_trajet_statut_positiongps'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='positiongps',
            name='modeles_pos_trajet__3118eb_idx',
        ),
        migrations.DeleteModel(
            name='PositionGPS',
        ),
    ]
