# Generated by Django 6.0.2 on 2026-05-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0008_remove_positiongps_modeles_pos_trajet__3118eb_idx_and_more'),
    ]

    operations = [
    ]
