# Generated by Django 6.0.2 on 2026-05-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0009_auto_20260509_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('vitesse_kmh', models.FloatField(blank=True, null=True)),
                ('direction', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_gps', to='modeles.trajet')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trajet', '-timestamp'], name='pos_trajet_timestamp_idx')],
            },
        ),
    ]
