# Generated by Django 6.0.2 on 2026-05-11 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0010_positiongps'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='positiongps',
            name='pos_trajet_timestamp_idx',
        ),
        migrations.AddField(
            model_name='paiement',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_conducteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='passager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.CharField(default='ESPECE', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_CONFIRMATION', 'En Attente Confirmation'), ('CONFIRME', 'Confirme'), ('ANNULE', 'Annule'), ('EN_ATTENTE', 'En Attente'), ('PAYEE', 'Payee'), ('ECHOUEE', 'Echouee')], default='EN_ATTENTE_CONFIRMATION', max_length=30),
        ),
        migrations.DeleteModel(
            name='PositionGPS',
        ),
    ]
