# Generated by Django 6.0.2 on 2026-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0012_economiemensuelle_revenumensuel_statistiqueeconomie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('declinee', 'Déclinée'), ('terminee', 'Terminée')], default='en_attente', max_length=20),
        ),
    ]
