# Generated by Django 6.0.2 on 2026-05-25 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0013_alter_reservation_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_plainte', models.CharField(choices=[('conducteur', 'Conducteur'), ('passager', 'Passager'), ('comportement', 'Comportement'), ('vehicule', 'Véhicule'), ('autre', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resolue', 'Résolue'), ('rejetee', 'Rejetée'), ('suspendue', 'Suspendue')], default='en_attente', max_length=20)),
                ('note_admin', models.TextField(blank=True, help_text="Notes de l'administrateur")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('admin_assigne', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes_assignees', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes', to='modeles.evaluation')),
                ('signalataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaintes_deposees', to=settings.AUTH_USER_MODEL)),
                ('trajet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes', to='modeles.trajet')),
                ('utilisateur_signale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaintes_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
