# Generated by Django 6.0.2 on 2026-06-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0014_plainte'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reference_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_cni',
            field=models.ImageField(blank=True, null=True, upload_to='documents/cni/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_permis',
            field=models.ImageField(blank=True, null=True, upload_to='documents/permis/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut_validation',
            field=models.CharField(choices=[('non_soumis', 'Non soumis'), ('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='non_soumis', max_length=20),
        ),
    ]
