# Generated by Django 6.0.2 on 2026-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0015_paiement_reference_mobile_utilisateur_photo_cni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='peut_conduire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='photo_carte_grise',
            field=models.ImageField(blank=True, null=True, upload_to='documents/carte_grise/'),
        ),
    ]
