# Generated by Django 6.0.2 on 2026-06-06 11:24

import apps.modeles.models
import apps.modeles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0017_alter_message_options_alter_evaluation_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_cni',
            field=models.ImageField(blank=True, null=True, upload_to='documents/cni/', validators=[apps.modeles.validators.valider_image_document]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_permis',
            field=models.ImageField(blank=True, null=True, upload_to='documents/permis/', validators=[apps.modeles.validators.valider_image_document]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=apps.modeles.models.chemin_photo, validators=[apps.modeles.validators.valider_image_profil]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='photo_carte_grise',
            field=models.ImageField(blank=True, null=True, upload_to='documents/carte_grise/', validators=[apps.modeles.validators.valider_image_document]),
        ),
    ]
