# Generated by Django 6.0.2 on 2026-06-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0020_blocage_eval_signalement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blocagepassager',
            new_name='modeles_blo_conduct_b4cdc9_idx',
            old_name='modeles_blo_conduct_idx',
        ),
        migrations.RenameIndex(
            model_name='blocagepassager',
            new_name='modeles_blo_passage_f438e6_idx',
            old_name='modeles_blo_passager_idx',
        ),
    ]
