# Generated by Django 6.0.2 on 2026-06-10 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0022_utilisateur_driver_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code_embarquement',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='depose_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='depose_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='distance_passager',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='heure_depose',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='heure_embarquement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='penalite_annulation',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='point_depose',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='point_prise_en_charge',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prise_en_charge_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prise_en_charge_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prix_passager',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut_embarquement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('embarque', 'Embarqué'), ('depose', 'Déposé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='trajet',
            name='polyline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trajet',
            name='tolerance_detour_km',
            field=models.FloatField(default=2.0),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('ordre', models.IntegerField(help_text='0=départ, 1,2…=escales, dernier=destination')),
                ('heure_prevue', models.DateTimeField(blank=True, null=True)),
                ('heure_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('arrive', 'Arrivé'), ('parti', 'Parti')], default='en_attente', max_length=20)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escales', to='modeles.trajet')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('trajet', 'ordre')},
            },
        ),
    ]
