# Generated by Django 6.0.2 on 2026-06-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0026_auditlog_sysconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='modeles_aud_admin_i_5ce15c_idx',
            old_name='auditlog_admin_date_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='modeles_aud_action_040631_idx',
            old_name='auditlog_action_date_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='modeles_aud_cible_t_03c79e_idx',
            old_name='auditlog_cible_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sysconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
