# Generated by Django 6.0.2 on 2026-06-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0028_paiement_payplus_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_CONFIRMATION', 'En Attente Confirmation'), ('EN_ATTENTE', 'En Attente'), ('PAYEE', 'Payee'), ('CONFIRME', 'Confirme'), ('ECHOUEE', 'Echouee'), ('ANNULE', 'Annule')], db_index=True, default='EN_ATTENTE_CONFIRMATION', max_length=30),
        ),
    ]
