# Generated by Django 6.0.2 on 2026-08-28 23:10

import apps.modeles.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0032_auth_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conducteur', 'Conducteur'), ('plateforme', 'Plateforme KoVoit')], max_length=20)),
                ('solde_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_du', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.modeles.validators.validate_positive_number])),
                ('moyen', models.CharField(choices=[('FLOOZ', 'Moov Flooz'), ('YAS', 'Mixx by Yas')], max_length=20)),
                ('numero_destination', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de traitement'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('reference_agregateur', models.CharField(blank=True, max_length=100)),
                ('motif_echec', models.CharField(blank=True, max_length=255)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_traites', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits', to='modeles.wallet')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL_REQUEST', 'Demande de retrait'), ('WITHDRAWAL_COMPLETED', 'Retrait effectué'), ('WITHDRAWAL_FAILED', 'Retrait échoué (remboursé)'), ('RIDE_PAYMENT_CREDIT', 'Crédit paiement de trajet'), ('COMMISSION_ELECTRONIC', 'Commission (paiement électronique)'), ('COMMISSION_CASH_DUE', 'Commission due (paiement espèces)'), ('COMMISSION_CASH_SETTLED', 'Commission espèces réglée'), ('REFUND', 'Remboursement'), ('CANCELLATION_PENALTY', "Pénalité d'annulation"), ('ADJUSTMENT', 'Ajustement manuel (admin)')], db_index=True, max_length=30)),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.modeles.validators.validate_positive_number])),
                ('solde_disponible_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_disponible_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_du_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_du_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], default='REUSSI', max_length=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_creees', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='modeles.paiement')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='modeles.reservation')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='modeles.wallet')),
                ('retrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='modeles.withdrawal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['type'], name='modeles_wal_type_dec4ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('solde_disponible__gte', 0)), name='wallet_solde_disponible_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('solde_du__gte', 0)), name='wallet_solde_du_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('proprietaire__isnull', True)), fields=('type',), name='wallet_unique_plateforme'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['wallet', '-date_demande'], name='modeles_wit_wallet__75b83f_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['statut'], name='modeles_wit_statut_0d3948_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='modeles_wal_wallet__e675e4_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['type', '-created_at'], name='modeles_wal_type_fe83ab_idx'),
        ),
    ]
