# Generated by Django 6.0.2 on 2026-08-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0033_wallet_withdrawal_wallettransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_suspend', 'Suspension utilisateur'), ('user_activate', 'Activation utilisateur'), ('user_ban', 'Bannissement utilisateur'), ('user_delete', 'Suppression utilisateur'), ('user_role', 'Changement de rôle'), ('doc_validate', 'Validation documents'), ('doc_reject', 'Rejet documents'), ('trip_cancel', 'Annulation trajet'), ('trip_delete', 'Suppression trajet'), ('trip_modify', 'Modification trajet'), ('resa_cancel', 'Annulation réservation'), ('resa_force', 'Forçage réservation'), ('payment_refund', 'Remboursement'), ('wallet_withdrawal_complete', 'Retrait traité — réussi'), ('wallet_withdrawal_fail', 'Retrait traité — échoué'), ('wallet_adjustment', 'Ajustement manuel wallet'), ('eval_hide', 'Masquage évaluation'), ('eval_restore', 'Restauration évaluation'), ('complaint_assign', 'Assignation plainte'), ('complaint_close', 'Fermeture plainte'), ('complaint_reject', 'Rejet plainte'), ('msg_read', 'Lecture messages admin'), ('config_update', 'Mise à jour configuration'), ('notif_send', 'Envoi notification'), ('admin_login', 'Connexion admin')], db_index=True, max_length=30),
        ),
    ]
