# Generated by Django 6.0.2 on 2026-08-29 00:34

import apps.modeles.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0035_alter_paiement_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.modeles.validators.validate_positive_number])),
                ('token', models.CharField(max_length=100, unique=True)),
                ('transref', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='modeles.wallet')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['wallet', '-date_creation'], name='modeles_dep_wallet__4253c4_idx')],
            },
        ),
    ]
