# Generated by Django 6.0.2 on 2026-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0036_depotwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotwallet',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_mobile',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
