# Generated by Django 6.0.2 on 2026-05-11 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomieMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('economie_totale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_reservations', models.IntegerField(default=0)),
                ('economie_moyenne_reservation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cout_transport_individuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cout_covoiturage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economies_mensuelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('passager', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='RevenuMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('revenu_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_trajets', models.IntegerField(default=0)),
                ('km_parcourus', models.FloatField(default=0)),
                ('revenu_moyen_trajet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenus_mensuels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('conducteur', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='StatistiqueEconomie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('total_revenus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_trajets', models.IntegerField(default=0)),
                ('total_km', models.FloatField(default=0)),
                ('moyenne_par_trajet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_economies', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_reservations', models.IntegerField(default=0)),
                ('moyenne_par_reservation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('economie_carburant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('co2_evite', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques_economie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periode_debut'],
                'unique_together': {('utilisateur', 'periode_debut', 'periode_fin')},
            },
        ),
    ]
