# Generated by Django 6.0.2 on 2026-05-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revenumensuel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='revenumensuel',
            name='conducteur',
        ),
        migrations.AlterUniqueTogether(
            name='statistiqueeconomie',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statistiqueeconomie',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='EconomieMensuelle',
        ),
        migrations.DeleteModel(
            name='RevenuMensuel',
        ),
        migrations.DeleteModel(
            name='StatistiqueEconomie',
        ),
    ]
