# Generated by Django 6.0.2 on 2026-06-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0003_conversation_type_groupe'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='messagerie__trajet__120c7a_idx',
            old_name='messagerie_trajet_type_idx',
        ),
    ]
