# Generated by Django 6.0.2 on 2026-06-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationhistory',
            new_name='chatbot_con_session_f19d66_idx',
            old_name='chatbot_session_idx',
        ),
    ]
